CUNY SPS Bridge:Math with Python
Name: Chinedu Onyeka
Date : July 30th,, 2021

HomeWork 2 problems:
Provide all solutions in an .html file. 

1.  Write a Python program to compute the eigenvalues and right eigenvectors of a given square array.

2.  Write a Python program to compute the factor of a given array by Singular Value Decomposition

3.  Write a Python program to compute the determinant of an array.

In [4]:
#import necessary libraries
import numpy as np
import scipy
from numpy import array
from numpy.linalg import eig, det
from scipy.linalg import svd

In [5]:
#Define the array
n = 3
A = np.random.randint(0,10,(n,n))
A

array([[8, 7, 4],
       [6, 9, 0],
       [3, 2, 7]])

In [11]:
#Problem 1: Compute the eigenvalues and eigenvectors of a given square array

#eigenvalues and eigenvectors
values, vectors = eig(A)
print('The eigen values are: \n', values)
print('------------------------------------------')
print('The eigen vectors are: \n', vectors)


The eigen values are: 
 [16.04346408  1.43327008  6.52326584]
------------------------------------------
The eigen vectors are: 
 [[-0.70778274 -0.76848259  0.21394246]
 [-0.60292725  0.60936436 -0.51828523]
 [-0.36813357  0.19521677  0.82801512]]


In [12]:
#Problem 2: Compute the factor of a given array by SVD

#factors by SVD
U, s, V = svd(A)
print('U: \n',U)
print('------------------------------------------')
print('s: \n',s)
print('------------------------------------------')
print('V: \n',V)

U: 
 [[-0.69937118 -0.09703521  0.70814132]
 [-0.62580886  0.56178025 -0.54107875]
 [-0.34531612 -0.821576   -0.45361841]]
------------------------------------------
s: 
 [16.15277937  6.72152934  1.38157956]
------------------------------------------
V: 
 [[-0.64297114 -0.69452507 -0.32283593]
 [ 0.01929202  0.4066967  -0.91335952]
 [ 0.76564739 -0.59349197 -0.24809545]]


In [16]:
#Problem 3: Compute the determinant of the array

#Determinant:
detA = det(A)
detA = round(detA,1)
print('detA:',detA)

detA: 150.0
